name: eff-cv
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - cuda-nvrtc=12.4.127
  - cuda-version=12.4
  - cudnn=9.1.1.17
  - ld_impl_linux-64=2.40
  - libcublas=12.4.5.8
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - nccl=2.21.5.1
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.10.16
  - readline=8.2
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - typing_extensions=4.12.2
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - accelerate==1.5.2
      - annotated-types==0.7.0
      - backoff==2.2.1
      - beautifulsoup4==4.13.3
      - botocore==1.35.77
      - braceexpand==0.1.7
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.8
      - colorama==0.4.6
      - contourpy==1.3.1
      - cycler==0.12.1
      - deprecation==2.1.0
      - docker-pycreds==0.4.0
      - efficient-cv==0.0.1
      - einops==0.8.1
      - filelock==3.18.0
      - fonttools==4.56.0
      - fsspec==2025.3.0
      - ftfy==6.3.1
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - h5py==3.12.1
      - huggingface-hub==0.29.3
      - idna==3.10
      - jinja2==3.1.6
      - jmespath==1.0.1
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==1.26.4
      - nvidia-cusparselt-cu12==0.6.2
      - open-clip-torch==2.31.0
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - platformdirs==4.3.7
      - prettytable==3.12.0
      - protobuf==3.20.3
      - psutil==7.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyparsing==3.2.1
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - pyyaml==6.0.2
      - qai-hub==0.20.0
      - regex==2024.11.6
      - requests-toolbelt==1.0.0
      - s3transfer==0.10.4
      - scipy==1.15.2
      - semver==3.0.2
      - sentry-sdk==2.23.1
      - setproctitle==1.3.5
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.6
      - timm==1.0.15
      - tokenizers==0.21.1
      - torch==2.6.0
      - torch-fidelity==0.3.0
      - torchinfo==1.8.0
      - torchvision==0.21.0
      - tqdm==4.67.1
      - transformers==4.49.0
      - triton==3.2.0
      - tzdata==2025.1
      - urllib3==2.2.3
      - wandb==0.19.8
      - wcwidth==0.2.13
      - webdataset==0.2.111
