[project]
name = "efficient-cv"
version = "0.0.1"
description = "A library for efficient computer vision on edge devices."
authors = [
    { name = "Michael Krah", email = "mickra@bu.edu" },
    { name = "Zach Gentile", email = "zgentile@bu.edu" },
    { name = "Alex Lavaee", email = "alavaee@bu.edu" },
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch>=2.0.0",
    "torchvision",
    "omegaconf",
    "transformers",
    "timm",
    "open_clip_torch",
    "einops",
    "scipy",
    "pillow",
    "accelerate",
    "gdown",
    "huggingface-hub",
    "einops",
    "wandb",
    "torch-fidelity",
    "torchinfo",
    "webdataset",
    "hf_transfer",
    "iopath",
    "termcolor",
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["efficient_cv"]
namespaces = true

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
