[project]
name = "efficient-cv"
version = "0.0.1"
description = "A library for efficient computer vision on edge devices."
authors = [
    { name = "Michael Krah", email = "mickra@bu.edu" },
    { name = "Zach Gentile", email = "zgentile@bu.edu" },
    { name = "Alex Lavaee", email = "alavaee@bu.edu" },
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
"accelerate==1.5.2",
"aiohappyeyeballs==2.6.1",
"aiohttp==3.11.14",
"aiosignal==1.3.2",
"annotated-types==0.7.0",
"antlr4-python3-runtime==4.9.3",
"async-timeout==5.0.1",
"attrs==25.3.0",
"backoff==2.2.1",
"beautifulsoup4==4.13.3",
"botocore==1.35.77",
"braceexpand==0.1.7",
"certifi==2024.8.30",
"charset-normalizer==3.4.0",
"click==8.1.8",
"colorama==0.4.6",
"contourpy==1.3.1",
"cycler==0.12.1",
"datasets==3.0.2",
"deprecation==2.1.0",
"dill==0.3.8",
"docker-pycreds==0.4.0",
"einops==0.8.1",
"evaluate==0.4.3",
"Farama-Notifications==0.0.4",
"filelock==3.18.0",
"fonttools==4.56.0",
"frozenlist==1.5.0",
"fsspec==2024.9.0",
"ftfy==6.3.1",
"gdown==5.2.0",
"gensim",
"gitdb==4.0.12",
"GitPython==3.1.44",
"gymnasium==1.0.0",
"h5py==3.12.1",
"huggingface-hub==0.29.3",
"idna==3.10",
"Jinja2==3.1.6",
"jmespath==1.0.1",
"kiwisolver==1.4.8",
"kneed==0.8.5",
"MarkupSafe==3.0.2",
"matplotlib==3.10.1",
"mpmath==1.3.0",
"multidict==6.2.0",
"multiprocess==0.70.16",
"networkx==3.4.2",
"numpy",
"nvidia-cublas-cu12==12.4.5.8",
"nvidia-cuda-cupti-cu12==12.4.127",
"nvidia-cuda-nvrtc-cu12==12.4.127",
"nvidia-cuda-runtime-cu12==12.4.127",
"nvidia-cudnn-cu12==9.1.0.70",
"nvidia-cufft-cu12==11.2.1.3",
"nvidia-curand-cu12==10.3.5.147",
"nvidia-cusolver-cu12==11.6.1.9",
"nvidia-cusparse-cu12==12.3.1.170",
"nvidia-cusparselt-cu12==0.6.2",
"nvidia-nccl-cu12==2.21.5",
"nvidia-nvjitlink-cu12==12.4.127",
"nvidia-nvtx-cu12==12.4.127",
"omegaconf==2.3.0",
"open_clip_torch==2.31.0",
"packaging==24.2",
"pandas==2.2.3",
"pillow==11.1.0",
"platformdirs==4.3.7",
"prettytable==3.12.0",
"propcache==0.3.0",
"protobuf==3.20.3",
"psutil==7.0.0",
"pyarrow==18.0.0",
"pydantic==2.10.6",
"pydantic_core==2.27.2",
"pyparsing==3.2.1",
"PySocks==1.7.1",
"python-dateutil==2.9.0.post0",
"pytz==2025.1",
"PyYAML==6.0.2",
"qai-hub==0.20.0",
"regex==2024.11.6",
"requests==2.32.3",
"requests-toolbelt==1.0.0",
"s3transfer==0.10.4",
"safetensors==0.4.5",
"scipy",
"semver==3.0.2",
"sentry-sdk==2.23.1",
"seqeval==1.2.2",
"setproctitle==1.3.5",
"six==1.17.0",
"smmap==5.0.2",
"soupsieve==2.6",
"sympy==1.13.1",
"timm==1.0.15",
"tokenizers==0.21.1",
"torch==2.6.0",
"torch-fidelity==0.3.0",
"torchinfo==1.8.0",
"torchvision==0.21.0",
"tqdm==4.67.1",
"transformers==4.49.0",
"triton==3.2.0",
"typing_extensions==4.12.2",
"tzdata==2025.1",
"urllib3==2.2.3",
"wandb==0.19.8",
"wcwidth==0.2.13",
"webdataset==0.2.111",
"xxhash==3.5.0",
"yarl==1.18.3",
]

[tool.uv.sources]
torch = [
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
    { index = "pytorch-cu124", marker = "sys_platform == 'linux'" },
]
torchvision = [
    { index = "pytorch-cpu", marker = "sys_platform != 'linux'" },
    { index = "pytorch-cu124", marker = "sys_platform == 'linux'" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu124"
url = "https://download.pytorch.org/whl/cu124"
explicit = true

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
